[package]
name = "http-dog-fetcher"
edition = "2021"
version = "0.1.0"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { version = "0.16", features = ["default"] }
wasmcloud-actor = { path = "../../../../crates/actor", features = ["component", "rand", "uuid"] }
serde = "1.0.193"
serde_json = "1.0.108"

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
strip = true
