apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: http-dog-fetcher
  annotations:
    version: v0.0.1
    description: "Rust actor that uses wasi:http and wasi:blobstore to fetch dog pictures"
    experimental: true
spec:
  components:
    - name: http-dog-fetcher
      type: actor
      properties:
        # TODO: you must replace the path below to match your genreated code in build
        # Try using `wash build -o json` and use the `actor_path` field, prepended with `file://`
        image: file:///the/absolute/path/to/build/http-hello-world-component_s.wasm
      traits:
        # Govern the spread/scheduling of the actor
        - type: spreadscaler
          properties:
            replicas: 1
        # Link the HTTP server, and inform it to listen on port 8081
        # on the local machine
        - type: linkdef
          properties:
            target: httpserver
            values:
              ADDRESS: 127.0.0.1:8081
        - type: linkdef
          properties:
            target: httpclient
        - type: linkdef
          properties:
            target: blobstore

    # Add a capability provider that mediates HTTP access
    - name: httpserver
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpserver:0.19.1
        contract: wasmcloud:httpserver
    - name: httpclient
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpclient:0.8.0
        contract: wasmcloud:httpclient
    - name: blobstore
      type: capability
      properties:
        image: wasmcloud.azurecr.io/blobstore_fs:0.5.1
        contract: wasmcloud:blobstore
